391 add utils functions for pose matrix
pollen-robotics/reachy2-sdk pull request #392
Opened 2024-09-27 12:46 UTC by glannuzel

Add of 2 utils functions to create matrix pose for the arms : 
- `reachy.r_arm.get_default_pose_matrix()`, which takes the same common_pose as `set_pose()`
- `reachy.r_arm.get_pose_matrix([x, y, z], [roll, pitch, yaw])` to create matrix the way they use `make_pose` in the tuto

Not sure putting them in arm in the right place.

2024-10-02 07:58 UTC, ClaireHzl approved these changes
amazing job ! 
But maybe the get_pose_matrix should be in utils, as it doesn't depend on the arm

2024-10-02 08:32 UTC, FabienDanieau requested changes
Well it works but I'd have done things a bit differently. What do you think?

2024-10-02 08:32 UTC, FabienDanieau commented on src/reachy2_sdk/parts/arm.py
> +        if common_pose == "elbow_90":
This is also defined in set_pose. We should factorize the poses somewhere otherwise we may do a mistake by changing one and not the other.

2024-10-02 08:32 UTC, FabienDanieau commented on src/reachy2_sdk/parts/arm.py
> +    def get_pose_matrix(
Is it for arms only? It seems that a generic function that builds a pose. It can go to utils right?

2024-10-03 09:13 UTC, apirrone requested changes
if the goal is to remove the FramesViewer utils dependency (I'm all for it), could we include `rotateInSelf` and `translateInSelf` ? I use them a lot. They are implemented here in FramesViewer https://github.com/apirrone/FramesViewer/blob/master/FramesViewer/utils.py

2024-10-04 13:51 UTC, apirrone approved these changes
Perfect 👌

2024-10-07 07:47 UTC, merged