Correction of TypeErrors
pollen-robotics/reachy2-sdk pull request #431
Opened 2024-10-16 10:53 UTC by ClaireHzl

Switch from ValueError to TypeError when needed, and correction of some docstrings

2024-10-22 08:43 UTC, glannuzel requested changes

2024-10-22 10:13 UTC, ClaireHzl commented
I added a function _check_goto_parameters for the GoToBased_Parts, to do the checks (because the function was too complex otherwise)

2024-10-22 15:01 UTC, FabienDanieau requested changes
Don't forget to add unit tests!

2024-10-22 15:01 UTC, FabienDanieau commented on src/reachy2_sdk/parts/head.py
> +    def _check_goto_parameters(self, duration: float, target: Any, q0: Optional[List[float]] = None) -> None:
same :)

2024-10-23 07:14 UTC, FabienDanieau approved these changes
Thanks that's perfect!

2024-10-24 13:19 UTC, glannuzel approved these changes

2024-10-24 13:23 UTC, merged