433 add rotate for head
pollen-robotics/reachy2-sdk pull request #434
Opened 2024-10-21 16:14 UTC by ClaireHzl

Rotate_by for the head, with frame "robot" and "head"

2024-10-22 09:43 UTC, glannuzel requested changes

2024-10-22 09:43 UTC, glannuzel commented on src/reachy2_sdk/parts/head.py
> +        joints_goal = NeckOrientation(rotation=Rotation3d(q=Quaternion(w=target.w, x=target.x, y=target.y, z=target.z)))
You could directly call the goto function with a pyQuat to avoid code duplication. It would check if the part is on as well and catch errors

2024-10-22 09:43 UTC, glannuzel commented on src/reachy2_sdk/parts/head.py
> +        current_quaternion = self.get_current_orientation()
I think it should work like rotate_by of the arm and do a rotate_by relative to the last command sent.

If we do:
```
reachy.goto_posture("default", wait=True)
reachy.head.goto([15, 20, 10])
reachy.head.rotate_by(roll=10)
```
the rotate_by will be a roll from the default posture, and not the previous goto

2024-10-22 15:04 UTC, FabienDanieau requested changes

2024-10-22 15:04 UTC, FabienDanieau commented on src/reachy2_sdk/utils/utils.py
> +def quaternion_from_euler(roll: float, pitch: float, yaw: float, degrees: bool = True) -> Quaternion:
offline tests needed sorry :)

2024-10-23 12:18 UTC, FabienDanieau approved these changes
Nice job! I would fix a test before merging though

2024-10-23 12:18 UTC, FabienDanieau commented on tests/units/offline/test_utils.py
> +    expected_quat = Quaternion(axis=[0.57735027, 0.57735027, 0.57735027], angle=np.pi / 4).normalised
q5 = quaternion_from_euler_angles(0, 0 0).normalised also pass the test

Why not:
```
    q5_ref = Quaternion(axis=[0.679, 0.281, 0.679], angle=np.deg2rad(85.8))
    unit_quat = Quaternion()
    expected_unit = q5 * q5_ref.inverse
    assert np.allclose(unit_quat.elements, expected_unit.elements, atol=1e-3)
```
A quaternion multiply by its inverse will give a unit quaternion

2024-10-24 13:15 UTC, glannuzel approved these changes

2024-10-24 13:20 UTC, merged